<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>4126a7d6-a181-4d49-801f-fb25b1e6a395</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Views\Shared\_Layout.cshtml.css" />
	  <None Remove="Views\Site\Index.cshtml~RF375af4b5.TMP" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Views\Shared\_Layout.cshtml.css" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
		<PackageReference Include="System.Data.SQLite" Version="1.0.119" />
	</ItemGroup>

</Project>
