apiVersion: apps/v1
kind: Deployment
metadata:
  name: pa-csharp-app
  labels:
    app: pa-csharp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pa-csharp-app
  template:
    metadata:
      labels:
        app: pa-csharp-app
    spec:
      containers:
      - name: pa-csharp-app
        image: ecos04/mvc-repo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pa-csharp-app-service
spec:
  selector:
    app: pa-csharp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
